/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Timestamp = IDL.Int;
export const CouponInput = IDL.Record({
  'expiryDate' : IDL.Opt(Timestamp),
  'code' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'isActive' : IDL.Bool,
  'maxUses' : IDL.Opt(IDL.Nat),
});
export const Coupon = IDL.Record({
  'expiryDate' : IDL.Opt(Timestamp),
  'code' : IDL.Text,
  'usageCount' : IDL.Nat,
  'discountPercent' : IDL.Nat,
  'isActive' : IDL.Bool,
  'maxUses' : IDL.Opt(IDL.Nat),
});
export const FaqItemInput = IDL.Record({
  'id' : IDL.Text,
  'question' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'answer' : IDL.Text,
  'isVisible' : IDL.Bool,
});
export const FaqItem = IDL.Record({
  'id' : IDL.Text,
  'question' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'answer' : IDL.Text,
  'isVisible' : IDL.Bool,
});
export const HeroSlideInput = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'isVisible' : IDL.Bool,
  'highlight' : IDL.Text,
  'subtitle' : IDL.Text,
});
export const HeroSlide = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'isVisible' : IDL.Bool,
  'highlight' : IDL.Text,
  'subtitle' : IDL.Text,
});
export const ProductVariant = IDL.Record({
  'variantLabel' : IDL.Text,
  'stock' : IDL.Nat,
  'variantId' : IDL.Text,
  'price' : IDL.Nat,
});
export const ProductInput = IDL.Record({
  'id' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'variants' : IDL.Vec(ProductVariant),
  'imageUrl' : IDL.Text,
  'shortDescription' : IDL.Text,
  'isVisible' : IDL.Bool,
  'category' : IDL.Text,
  'benefits' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
  'longDescription' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'variants' : IDL.Vec(ProductVariant),
  'imageUrl' : IDL.Text,
  'shortDescription' : IDL.Text,
  'isVisible' : IDL.Bool,
  'category' : IDL.Text,
  'benefits' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
  'longDescription' : IDL.Text,
});
export const CouponValidation = IDL.Variant({
  'Exhausted' : IDL.Null,
  'Inactive' : IDL.Null,
  'NotFound' : IDL.Null,
  'Valid' : IDL.Nat,
  'Expired' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Confirmed' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Shipped' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'WhatsApp' : IDL.Null,
  'Stripe' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'variantLabel' : IDL.Text,
  'productId' : IDL.Text,
  'productName' : IDL.Text,
  'variantId' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const AnalyticsSummary = IDL.Record({
  'totalOrders' : IDL.Nat,
  'pendingOrders' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'deliveredOrders' : IDL.Nat,
});
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const SiteSettings = IDL.Record({
  'announcementBannerText' : IDL.Text,
  'whatsappOrderEnabled' : IDL.Bool,
  'maintenanceMode' : IDL.Bool,
  'whatsappNumber' : IDL.Text,
  'stripeEnabled' : IDL.Bool,
  'contactEmail' : IDL.Text,
  'footerText' : IDL.Text,
  'showAnnouncementBanner' : IDL.Bool,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const TopProduct = IDL.Record({
  'revenue' : IDL.Nat,
  'productId' : IDL.Text,
  'productName' : IDL.Text,
  'orderCount' : IDL.Nat,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const OrderInput = IDL.Record({
  'customerName' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'email' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const SiteSettingsInput = IDL.Record({
  'announcementBannerText' : IDL.Opt(IDL.Text),
  'whatsappOrderEnabled' : IDL.Opt(IDL.Bool),
  'maintenanceMode' : IDL.Opt(IDL.Bool),
  'whatsappNumber' : IDL.Opt(IDL.Text),
  'stripeEnabled' : IDL.Opt(IDL.Bool),
  'contactEmail' : IDL.Opt(IDL.Text),
  'footerText' : IDL.Opt(IDL.Text),
  'showAnnouncementBanner' : IDL.Opt(IDL.Bool),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addCoupon' : IDL.Func(
      [CouponInput],
      [IDL.Variant({ 'ok' : Coupon, 'err' : IDL.Text })],
      [],
    ),
  'addFAQ' : IDL.Func(
      [FaqItemInput],
      [IDL.Variant({ 'ok' : FaqItem, 'err' : IDL.Text })],
      [],
    ),
  'addHeroSlide' : IDL.Func(
      [HeroSlideInput],
      [IDL.Variant({ 'ok' : HeroSlide, 'err' : IDL.Text })],
      [],
    ),
  'addProduct' : IDL.Func(
      [ProductInput],
      [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
      [],
    ),
  'applyCoupon' : IDL.Func([IDL.Text], [CouponValidation], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkIsAdmin' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCoupon' : IDL.Func(
      [CouponInput],
      [IDL.Variant({ 'ok' : Coupon, 'err' : IDL.Text })],
      [],
    ),
  'deleteCoupon' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteFAQ' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteFaqItem' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteHeroSlide' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteProduct' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'getAdminCoupons' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(Coupon), 'err' : IDL.Text })],
      [],
    ),
  'getAdminOrders' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(Order), 'err' : IDL.Text })],
      [],
    ),
  'getAdminPrincipal' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Opt(IDL.Text), 'err' : IDL.Text })],
      [],
    ),
  'getAdminProducts' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(Product), 'err' : IDL.Text })],
      [],
    ),
  'getAnalyticsSummary' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : AnalyticsSummary, 'err' : IDL.Text })],
      [],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactMessages' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(ContactMessage), 'err' : IDL.Text })],
      [],
    ),
  'getCoupons' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(Coupon), 'err' : IDL.Text })],
      [],
    ),
  'getDashboardStats' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : AnalyticsSummary, 'err' : IDL.Text })],
      [],
    ),
  'getFAQs' : IDL.Func([], [IDL.Vec(FaqItem)], ['query']),
  'getFaqItems' : IDL.Func([], [IDL.Vec(FaqItem)], ['query']),
  'getHeroSlides' : IDL.Func([], [IDL.Vec(HeroSlide)], ['query']),
  'getImageUploadUrl' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'publicUrl' : IDL.Text, 'uploadUrl' : IDL.Text }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'getOrder' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Opt(Order), 'err' : IDL.Text })],
      [],
    ),
  'getOrders' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(Order), 'err' : IDL.Text })],
      [],
    ),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getRecentOrders' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Vec(Order), 'err' : IDL.Text })],
      [],
    ),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTopProducts' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Vec(TopProduct), 'err' : IDL.Text })],
      [],
    ),
  'hasAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'setAdminPrincipal' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'setAdminPrincipalExplicit' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'storeOrder' : IDL.Func(
      [OrderInput],
      [IDL.Variant({ 'ok' : Order, 'err' : IDL.Text })],
      [],
    ),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : ContactMessage, 'err' : IDL.Text })],
      [],
    ),
  'toggleCoupon' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : Coupon, 'err' : IDL.Text })],
      [],
    ),
  'toggleProductVisibility' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCoupon' : IDL.Func(
      [IDL.Text, CouponInput],
      [IDL.Variant({ 'ok' : Coupon, 'err' : IDL.Text })],
      [],
    ),
  'updateFAQ' : IDL.Func(
      [IDL.Text, FaqItemInput],
      [IDL.Variant({ 'ok' : FaqItem, 'err' : IDL.Text })],
      [],
    ),
  'updateHeroSlide' : IDL.Func(
      [IDL.Text, HeroSlideInput],
      [IDL.Variant({ 'ok' : HeroSlide, 'err' : IDL.Text })],
      [],
    ),
  'updateOrderStatus' : IDL.Func(
      [IDL.Text, OrderStatus],
      [IDL.Variant({ 'ok' : Order, 'err' : IDL.Text })],
      [],
    ),
  'updateProduct' : IDL.Func(
      [IDL.Text, ProductInput],
      [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
      [],
    ),
  'updateSiteSettings' : IDL.Func(
      [SiteSettings],
      [IDL.Variant({ 'ok' : SiteSettings, 'err' : IDL.Text })],
      [],
    ),
  'updateSiteSettingsPartial' : IDL.Func(
      [SiteSettingsInput],
      [IDL.Variant({ 'ok' : SiteSettings, 'err' : IDL.Text })],
      [],
    ),
  'upsertFaqItem' : IDL.Func(
      [FaqItemInput],
      [IDL.Variant({ 'ok' : FaqItem, 'err' : IDL.Text })],
      [],
    ),
  'upsertHeroSlide' : IDL.Func(
      [HeroSlideInput],
      [IDL.Variant({ 'ok' : HeroSlide, 'err' : IDL.Text })],
      [],
    ),
  'validateCoupon' : IDL.Func([IDL.Text], [CouponValidation], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Timestamp = IDL.Int;
  const CouponInput = IDL.Record({
    'expiryDate' : IDL.Opt(Timestamp),
    'code' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'isActive' : IDL.Bool,
    'maxUses' : IDL.Opt(IDL.Nat),
  });
  const Coupon = IDL.Record({
    'expiryDate' : IDL.Opt(Timestamp),
    'code' : IDL.Text,
    'usageCount' : IDL.Nat,
    'discountPercent' : IDL.Nat,
    'isActive' : IDL.Bool,
    'maxUses' : IDL.Opt(IDL.Nat),
  });
  const FaqItemInput = IDL.Record({
    'id' : IDL.Text,
    'question' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'answer' : IDL.Text,
    'isVisible' : IDL.Bool,
  });
  const FaqItem = IDL.Record({
    'id' : IDL.Text,
    'question' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'answer' : IDL.Text,
    'isVisible' : IDL.Bool,
  });
  const HeroSlideInput = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'isVisible' : IDL.Bool,
    'highlight' : IDL.Text,
    'subtitle' : IDL.Text,
  });
  const HeroSlide = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'isVisible' : IDL.Bool,
    'highlight' : IDL.Text,
    'subtitle' : IDL.Text,
  });
  const ProductVariant = IDL.Record({
    'variantLabel' : IDL.Text,
    'stock' : IDL.Nat,
    'variantId' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ProductInput = IDL.Record({
    'id' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'variants' : IDL.Vec(ProductVariant),
    'imageUrl' : IDL.Text,
    'shortDescription' : IDL.Text,
    'isVisible' : IDL.Bool,
    'category' : IDL.Text,
    'benefits' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
    'longDescription' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'variants' : IDL.Vec(ProductVariant),
    'imageUrl' : IDL.Text,
    'shortDescription' : IDL.Text,
    'isVisible' : IDL.Bool,
    'category' : IDL.Text,
    'benefits' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
    'longDescription' : IDL.Text,
  });
  const CouponValidation = IDL.Variant({
    'Exhausted' : IDL.Null,
    'Inactive' : IDL.Null,
    'NotFound' : IDL.Null,
    'Valid' : IDL.Nat,
    'Expired' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Confirmed' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Shipped' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'WhatsApp' : IDL.Null,
    'Stripe' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'variantLabel' : IDL.Text,
    'productId' : IDL.Text,
    'productName' : IDL.Text,
    'variantId' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'paymentMethod' : PaymentMethod,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const AnalyticsSummary = IDL.Record({
    'totalOrders' : IDL.Nat,
    'pendingOrders' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'deliveredOrders' : IDL.Nat,
  });
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const SiteSettings = IDL.Record({
    'announcementBannerText' : IDL.Text,
    'whatsappOrderEnabled' : IDL.Bool,
    'maintenanceMode' : IDL.Bool,
    'whatsappNumber' : IDL.Text,
    'stripeEnabled' : IDL.Bool,
    'contactEmail' : IDL.Text,
    'footerText' : IDL.Text,
    'showAnnouncementBanner' : IDL.Bool,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const TopProduct = IDL.Record({
    'revenue' : IDL.Nat,
    'productId' : IDL.Text,
    'productName' : IDL.Text,
    'orderCount' : IDL.Nat,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const OrderInput = IDL.Record({
    'customerName' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'email' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const SiteSettingsInput = IDL.Record({
    'announcementBannerText' : IDL.Opt(IDL.Text),
    'whatsappOrderEnabled' : IDL.Opt(IDL.Bool),
    'maintenanceMode' : IDL.Opt(IDL.Bool),
    'whatsappNumber' : IDL.Opt(IDL.Text),
    'stripeEnabled' : IDL.Opt(IDL.Bool),
    'contactEmail' : IDL.Opt(IDL.Text),
    'footerText' : IDL.Opt(IDL.Text),
    'showAnnouncementBanner' : IDL.Opt(IDL.Bool),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addCoupon' : IDL.Func(
        [CouponInput],
        [IDL.Variant({ 'ok' : Coupon, 'err' : IDL.Text })],
        [],
      ),
    'addFAQ' : IDL.Func(
        [FaqItemInput],
        [IDL.Variant({ 'ok' : FaqItem, 'err' : IDL.Text })],
        [],
      ),
    'addHeroSlide' : IDL.Func(
        [HeroSlideInput],
        [IDL.Variant({ 'ok' : HeroSlide, 'err' : IDL.Text })],
        [],
      ),
    'addProduct' : IDL.Func(
        [ProductInput],
        [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
        [],
      ),
    'applyCoupon' : IDL.Func([IDL.Text], [CouponValidation], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkIsAdmin' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCoupon' : IDL.Func(
        [CouponInput],
        [IDL.Variant({ 'ok' : Coupon, 'err' : IDL.Text })],
        [],
      ),
    'deleteCoupon' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteFAQ' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteFaqItem' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteHeroSlide' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteProduct' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'getAdminCoupons' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(Coupon), 'err' : IDL.Text })],
        [],
      ),
    'getAdminOrders' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(Order), 'err' : IDL.Text })],
        [],
      ),
    'getAdminPrincipal' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Opt(IDL.Text), 'err' : IDL.Text })],
        [],
      ),
    'getAdminProducts' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(Product), 'err' : IDL.Text })],
        [],
      ),
    'getAnalyticsSummary' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : AnalyticsSummary, 'err' : IDL.Text })],
        [],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactMessages' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(ContactMessage), 'err' : IDL.Text })],
        [],
      ),
    'getCoupons' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(Coupon), 'err' : IDL.Text })],
        [],
      ),
    'getDashboardStats' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : AnalyticsSummary, 'err' : IDL.Text })],
        [],
      ),
    'getFAQs' : IDL.Func([], [IDL.Vec(FaqItem)], ['query']),
    'getFaqItems' : IDL.Func([], [IDL.Vec(FaqItem)], ['query']),
    'getHeroSlides' : IDL.Func([], [IDL.Vec(HeroSlide)], ['query']),
    'getImageUploadUrl' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'publicUrl' : IDL.Text,
              'uploadUrl' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'getOrder' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Opt(Order), 'err' : IDL.Text })],
        [],
      ),
    'getOrders' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(Order), 'err' : IDL.Text })],
        [],
      ),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getRecentOrders' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Vec(Order), 'err' : IDL.Text })],
        [],
      ),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTopProducts' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Vec(TopProduct), 'err' : IDL.Text })],
        [],
      ),
    'hasAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'setAdminPrincipal' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'setAdminPrincipalExplicit' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'storeOrder' : IDL.Func(
        [OrderInput],
        [IDL.Variant({ 'ok' : Order, 'err' : IDL.Text })],
        [],
      ),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : ContactMessage, 'err' : IDL.Text })],
        [],
      ),
    'toggleCoupon' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : Coupon, 'err' : IDL.Text })],
        [],
      ),
    'toggleProductVisibility' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCoupon' : IDL.Func(
        [IDL.Text, CouponInput],
        [IDL.Variant({ 'ok' : Coupon, 'err' : IDL.Text })],
        [],
      ),
    'updateFAQ' : IDL.Func(
        [IDL.Text, FaqItemInput],
        [IDL.Variant({ 'ok' : FaqItem, 'err' : IDL.Text })],
        [],
      ),
    'updateHeroSlide' : IDL.Func(
        [IDL.Text, HeroSlideInput],
        [IDL.Variant({ 'ok' : HeroSlide, 'err' : IDL.Text })],
        [],
      ),
    'updateOrderStatus' : IDL.Func(
        [IDL.Text, OrderStatus],
        [IDL.Variant({ 'ok' : Order, 'err' : IDL.Text })],
        [],
      ),
    'updateProduct' : IDL.Func(
        [IDL.Text, ProductInput],
        [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
        [],
      ),
    'updateSiteSettings' : IDL.Func(
        [SiteSettings],
        [IDL.Variant({ 'ok' : SiteSettings, 'err' : IDL.Text })],
        [],
      ),
    'updateSiteSettingsPartial' : IDL.Func(
        [SiteSettingsInput],
        [IDL.Variant({ 'ok' : SiteSettings, 'err' : IDL.Text })],
        [],
      ),
    'upsertFaqItem' : IDL.Func(
        [FaqItemInput],
        [IDL.Variant({ 'ok' : FaqItem, 'err' : IDL.Text })],
        [],
      ),
    'upsertHeroSlide' : IDL.Func(
        [HeroSlideInput],
        [IDL.Variant({ 'ok' : HeroSlide, 'err' : IDL.Text })],
        [],
      ),
    'validateCoupon' : IDL.Func([IDL.Text], [CouponValidation], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };