/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsSummary {
  'totalOrders' : bigint,
  'pendingOrders' : bigint,
  'totalRevenue' : bigint,
  'deliveredOrders' : bigint,
}
export interface ContactMessage {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface Coupon {
  'expiryDate' : [] | [Timestamp],
  'code' : string,
  'usageCount' : bigint,
  'discountPercent' : bigint,
  'isActive' : boolean,
  'maxUses' : [] | [bigint],
}
export interface CouponInput {
  'expiryDate' : [] | [Timestamp],
  'code' : string,
  'discountPercent' : bigint,
  'isActive' : boolean,
  'maxUses' : [] | [bigint],
}
export type CouponValidation = { 'Exhausted' : null } |
  { 'Inactive' : null } |
  { 'NotFound' : null } |
  { 'Valid' : bigint } |
  { 'Expired' : null };
export interface FaqItem {
  'id' : string,
  'question' : string,
  'displayOrder' : bigint,
  'answer' : string,
  'isVisible' : boolean,
}
export interface FaqItemInput {
  'id' : string,
  'question' : string,
  'displayOrder' : bigint,
  'answer' : string,
  'isVisible' : boolean,
}
export interface HeroSlide {
  'id' : string,
  'title' : string,
  'displayOrder' : bigint,
  'imageUrl' : string,
  'isVisible' : boolean,
  'highlight' : string,
  'subtitle' : string,
}
export interface HeroSlideInput {
  'id' : string,
  'title' : string,
  'displayOrder' : bigint,
  'imageUrl' : string,
  'isVisible' : boolean,
  'highlight' : string,
  'subtitle' : string,
}
export interface Order {
  'id' : string,
  'customerName' : string,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Timestamp,
  'email' : string,
  'totalAmount' : bigint,
  'address' : string,
  'phone' : string,
  'items' : Array<OrderItem>,
}
export interface OrderInput {
  'customerName' : string,
  'paymentMethod' : PaymentMethod,
  'email' : string,
  'totalAmount' : bigint,
  'address' : string,
  'phone' : string,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'variantLabel' : string,
  'productId' : string,
  'productName' : string,
  'variantId' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export type OrderStatus = { 'Delivered' : null } |
  { 'Confirmed' : null } |
  { 'Cancelled' : null } |
  { 'Shipped' : null } |
  { 'Pending' : null };
export type PaymentMethod = { 'WhatsApp' : null } |
  { 'Stripe' : null };
export interface Product {
  'id' : string,
  'displayOrder' : bigint,
  'name' : string,
  'description' : string,
  'variants' : Array<ProductVariant>,
  'imageUrl' : string,
  'shortDescription' : string,
  'isVisible' : boolean,
  'category' : string,
  'benefits' : Array<string>,
  'price' : bigint,
  'longDescription' : string,
}
export interface ProductInput {
  'id' : string,
  'displayOrder' : bigint,
  'name' : string,
  'description' : string,
  'variants' : Array<ProductVariant>,
  'imageUrl' : string,
  'shortDescription' : string,
  'isVisible' : boolean,
  'category' : string,
  'benefits' : Array<string>,
  'price' : bigint,
  'longDescription' : string,
}
export interface ProductVariant {
  'variantLabel' : string,
  'stock' : bigint,
  'variantId' : string,
  'price' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SiteSettings {
  'announcementBannerText' : string,
  'whatsappOrderEnabled' : boolean,
  'maintenanceMode' : boolean,
  'whatsappNumber' : string,
  'stripeEnabled' : boolean,
  'contactEmail' : string,
  'footerText' : string,
  'showAnnouncementBanner' : boolean,
}
export interface SiteSettingsInput {
  'announcementBannerText' : [] | [string],
  'whatsappOrderEnabled' : [] | [boolean],
  'maintenanceMode' : [] | [boolean],
  'whatsappNumber' : [] | [string],
  'stripeEnabled' : [] | [boolean],
  'contactEmail' : [] | [string],
  'footerText' : [] | [string],
  'showAnnouncementBanner' : [] | [boolean],
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TopProduct {
  'revenue' : bigint,
  'productId' : string,
  'productName' : string,
  'orderCount' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addCoupon' : ActorMethod<
    [CouponInput],
    { 'ok' : Coupon } |
      { 'err' : string }
  >,
  'addFAQ' : ActorMethod<
    [FaqItemInput],
    { 'ok' : FaqItem } |
      { 'err' : string }
  >,
  'addHeroSlide' : ActorMethod<
    [HeroSlideInput],
    { 'ok' : HeroSlide } |
      { 'err' : string }
  >,
  'addProduct' : ActorMethod<
    [ProductInput],
    { 'ok' : Product } |
      { 'err' : string }
  >,
  'applyCoupon' : ActorMethod<[string], CouponValidation>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkIsAdmin' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCoupon' : ActorMethod<
    [CouponInput],
    { 'ok' : Coupon } |
      { 'err' : string }
  >,
  'deleteCoupon' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteFAQ' : ActorMethod<[string], { 'ok' : boolean } | { 'err' : string }>,
  'deleteFaqItem' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteHeroSlide' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteProduct' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'getAdminCoupons' : ActorMethod<
    [],
    { 'ok' : Array<Coupon> } |
      { 'err' : string }
  >,
  'getAdminOrders' : ActorMethod<
    [],
    { 'ok' : Array<Order> } |
      { 'err' : string }
  >,
  'getAdminPrincipal' : ActorMethod<
    [],
    { 'ok' : [] | [string] } |
      { 'err' : string }
  >,
  'getAdminProducts' : ActorMethod<
    [],
    { 'ok' : Array<Product> } |
      { 'err' : string }
  >,
  'getAnalyticsSummary' : ActorMethod<
    [],
    { 'ok' : AnalyticsSummary } |
      { 'err' : string }
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactMessages' : ActorMethod<
    [],
    { 'ok' : Array<ContactMessage> } |
      { 'err' : string }
  >,
  'getCoupons' : ActorMethod<[], { 'ok' : Array<Coupon> } | { 'err' : string }>,
  'getDashboardStats' : ActorMethod<
    [],
    { 'ok' : AnalyticsSummary } |
      { 'err' : string }
  >,
  'getFAQs' : ActorMethod<[], Array<FaqItem>>,
  'getFaqItems' : ActorMethod<[], Array<FaqItem>>,
  'getHeroSlides' : ActorMethod<[], Array<HeroSlide>>,
  'getImageUploadUrl' : ActorMethod<
    [string, string],
    { 'ok' : { 'publicUrl' : string, 'uploadUrl' : string } } |
      { 'err' : string }
  >,
  'getOrder' : ActorMethod<
    [string],
    { 'ok' : [] | [Order] } |
      { 'err' : string }
  >,
  'getOrders' : ActorMethod<[], { 'ok' : Array<Order> } | { 'err' : string }>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getRecentOrders' : ActorMethod<
    [bigint],
    { 'ok' : Array<Order> } |
      { 'err' : string }
  >,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTopProducts' : ActorMethod<
    [bigint],
    { 'ok' : Array<TopProduct> } |
      { 'err' : string }
  >,
  'hasAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'setAdminPrincipal' : ActorMethod<[], { 'ok' : string } | { 'err' : string }>,
  'setAdminPrincipalExplicit' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'storeOrder' : ActorMethod<
    [OrderInput],
    { 'ok' : Order } |
      { 'err' : string }
  >,
  'submitContact' : ActorMethod<
    [string, string, string],
    { 'ok' : ContactMessage } |
      { 'err' : string }
  >,
  'toggleCoupon' : ActorMethod<
    [string],
    { 'ok' : Coupon } |
      { 'err' : string }
  >,
  'toggleProductVisibility' : ActorMethod<
    [string],
    { 'ok' : Product } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCoupon' : ActorMethod<
    [string, CouponInput],
    { 'ok' : Coupon } |
      { 'err' : string }
  >,
  'updateFAQ' : ActorMethod<
    [string, FaqItemInput],
    { 'ok' : FaqItem } |
      { 'err' : string }
  >,
  'updateHeroSlide' : ActorMethod<
    [string, HeroSlideInput],
    { 'ok' : HeroSlide } |
      { 'err' : string }
  >,
  'updateOrderStatus' : ActorMethod<
    [string, OrderStatus],
    { 'ok' : Order } |
      { 'err' : string }
  >,
  'updateProduct' : ActorMethod<
    [string, ProductInput],
    { 'ok' : Product } |
      { 'err' : string }
  >,
  'updateSiteSettings' : ActorMethod<
    [SiteSettings],
    { 'ok' : SiteSettings } |
      { 'err' : string }
  >,
  'updateSiteSettingsPartial' : ActorMethod<
    [SiteSettingsInput],
    { 'ok' : SiteSettings } |
      { 'err' : string }
  >,
  'upsertFaqItem' : ActorMethod<
    [FaqItemInput],
    { 'ok' : FaqItem } |
      { 'err' : string }
  >,
  'upsertHeroSlide' : ActorMethod<
    [HeroSlideInput],
    { 'ok' : HeroSlide } |
      { 'err' : string }
  >,
  'validateCoupon' : ActorMethod<[string], CouponValidation>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];